services:
  # 生产环境服务
  viewanywhere:
    build:
      context: .
      dockerfile: Dockerfile.cn
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: viewanywhere-prod
    networks:
      - viewanywhere-network
    environment:
      - NODE_ENV=production
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 开发环境服务（可选）
  viewanywhere-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    container_name: viewanywhere-dev
    networks:
      - viewanywhere-network
    environment:
      - NODE_ENV=development
    profiles:
      - dev

networks:
  viewanywhere-network:
    driver: bridge

# 如果需要持久化数据，可以添加volumes
# volumes:
#   viewanywhere-data:
#     driver: local